package clover.command;

/**
 * Describes the visual treatment for a response generated by a command.
 */
public enum CommandResponseStyle {
    STANDARD,
    TASK_ADDED,
    TASK_MARKED,
    TASK_DELETED
}
